### ISSUE TITLE
`apodro_preprocess_field()`?

### ISSUE THREAD

**Issue by Schnitzel** [liip/bund_drupal_starterkit_theme#10]
there are some strange functions that have wrong names:
https://github.com/liip/bund_drupal_starterkit_theme/blob/master/bund_drupal_starterkit_theme.theme#L114
`apodro_preprocess_field()`

they should probably not be there? :)

**Comment by kchor** [comment]
You're right, we will replace `apodro` occurrences by `bund_drupal_starterkit_theme` :)

**Comment by sylvainaerni** [comment]
fixed
